### ISSUE TITLE
Gin的問題處理？！

### ISSUE THREAD

**Issue by mikeqoo1** [mikeqoo1/BackendServer#1]
1.跨域問題

2. 傳遞的訊息格式

@106062

**Comment by 106062** [comment]
目前看起來比較像是一個 API server 服務, 
下面根據你的誰來更新的部分要不要考
慮 Restful 的方式設定你的 API 街口 我看你也有引入其他的delete,update

**Comment by mikeqoo1** [comment]
....凌晨2點 不用上班喔！？

好的 我考慮看看 看你要不要改寫給閃電的後台

哈哈 比較好維護
